### ISSUE TITLE
feat: automatically sync changes of submodules

### ISSUE THREAD

**Issue by hwakabh** [hwakabh/gists#99]
### Submodule(s)

Nothing above

### AsIs

As noted in README, there is no feature to automatically apply changes from submodules into this repository, so we need to manually sync with `git submodule update --remote` command.

### ToDo

- [ ] research related GitHub Actions
- [ ] issue dedicated PAT for this operation
- [ ] add workflows into this repository

**Comment by hwakabh** [comment]
Validated this implementations with the following commit. (https://github.com/hwakabh/gists/commit/41470627d3fb40465a62074de86d6798266dc916)

As we intendedly updated the Gist codes, outside this repository in gist `translate_client_googleapis.py`, then manually ran the workflow via `workflow_dispatch`.
Changes: https://gist.github.com/hwakabh/702dd853b045eafb37a21b6de0737d63/revisions
Runs: https://github.com/hwakabh/gists/actions/runs/15178794356/job/42683968726

For checking the hash of the change with cloning Gist as general repo, confirmed the changes from GitHub Actions has been valid one.

```shell
% gh gist list  
ID                                DESCRIPTION                                        FILES    VISIBILITY  UPDATED            
702dd853b045eafb37a21b6de0737d63  Example of BeautifulSoup libs                      2 files  secret      about 1 hour ago
# ...

% gh gist clone 702dd853b045eafb37a21b6de0737d63
Cloning into '702dd853b045eafb37a21b6de0737d63'...
remote: Enumerating objects: 12, done.
remote: Total 12 (delta 0), reused 0 (delta 0), pack-reused 12 (from 1)
Receiving objects: 100% (12/12), done.
Resolving deltas: 100% (1/1), done.

% cd 702dd853b045eafb37a21b6de0737d63 
% git graph
* 8ff56a0  (HEAD -> main, origin/main, origin/HEAD) 2025-05-22 GitHub 
* ca268eb  2024-02-29 GitHub 
* b45b2b3  2024-02-29 GitHub 
* d0c7caf  2024-02-14 GitHub 
```

Seems there is a few difficulties on `actions/checkout@v4` with submodules, we prioritized the implementations with general `git` commands.
Note that once we provide Fine-grained Token in `git clone --recursive`, this token will be also used for cloning submodules(gists), so:
- we have to add permission to access gist to PAT
- we have to replace submodule URL with `https://` instead of git protocol (changes in be0a3a4), because this will trigger the error saying `Host key verification failed.`

**Comment by hwakabh** [comment]
Also validated the workflow runs when there is no changes between repo and Gists side.
https://github.com/hwakabh/gists/actions/runs/15178953558/job/42684377358

So now we can periodically schedule this workflow as daily basis, and resolved the issue for now.
